# Generated by Django 3.1.6 on 2021-02-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='instagram',
            new_name='location',
        ),
        migrations.AddField(
            model_name='post',
            name='mobile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
